PROYECTO-FINANZAS/PROYECTO-FINANZAS.Web/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using PROYECTO_FINANZAS.Web.Filters;
using PROYECTO_FINANZAS.Web.Helpers;

namespace PROYECTO_FINANZAS.Web.Controllers
{
    public class DashboardController : BaseController
    {
        [RolAuthFilter()]
        public ActionResult Index()
        {
            return View();
        }
    }
}

PROYECTO-FINANZAS/PROYECTO-FINANZAS.Web/Controllers/PerfilController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using PROYECTO_FINANZAS.Web.ViewModel.Perfil;
using System.Transactions;
using PROYECTO_FINANZAS.Web.Models;
using PROYECTO_FINANZAS.Web.Helpers;
using PROYECTO_FINANZAS.Web.Filters;

namespace PROYECTO_FINANZAS.Web.Controllers
{
    public class PerfilController : BaseController
    {
        [RolAuthFilter()]
        public ActionResult SeleccionarPerfil(int? perfilId)
        {
            var ObjUsuario = Context.Perfil.FirstOrDefault(X => X.PerfilId == perfilId);
            Session["PerfilId"] = ObjUsuario.PerfilId;
            Session["NombrePerfil"] = ObjUsuario.Nombre;
            TempData["Mensaje"] = "¡Perfil seleccionado exitosamente! Bienvenido " + ObjUsuario.Nombre;
            return RedirectToAction("ListarPerfiles");
        }
        [RolAuthFilter()]
        public ActionResult ListarPerfiles()
        {
            ListarPerfilesViewModel ViewModel = new ListarPerfilesViewModel();
            ViewModel.CargarDatos(Session.GetUsuarioId());
            return View(ViewModel);
        }

        [RolAuthFilter()]
        public ActionResult Delete(int? PerfilId)
        {
            try
            {
                int UsuarioId = Session.GetUsuarioId();
                int ContPerfiles = Context.Perfil.Where(X => X.UsuarioId == UsuarioId).Count();
                if (ContPerfiles == 1)
                {
                    TempData["Mensaje"] = "Debe tener al menos un perfil en su cuenta";
                    return RedirectToAction("ListarPerfiles");
                }

                using (var tc = new TransactionScope())
                {
                    if (PerfilId.HasValue)
                    {
                        Perfil ObjPerfil = Context.Perfil.FirstOrDefault(X => X.PerfilId == PerfilId);
                        Context.Perfil.Remove(ObjPerfil);
                        Context.SaveChanges();
                        TempData["Mensaje"] = "El perfil fue eliminado exitosamente";
                        tc.Complete();
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["Mensaje"] = "Error al eliminar el perfil, vuelva a intentarlo.";
            }
            return RedirectToAction("ListarPerfiles");
        }

        [RolAuthFilter()]
        public ActionResult Edit(int? PerfilId)
        {
            PerfilViewModel ViewModel = new PerfilViewModel();
            ViewModel.CargarDatos(PerfilId);
            return View(ViewModel);
        }

        [HttpPost]
        public ActionResult Edit(PerfilViewModel ViewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    ViewModel.CargarDatos(ViewModel.PerfilId);
                    TryUpdateModel(ViewModel);

                    TempData["Mensaje"] = "Por favor, complete los campos requeridos";
                    return View(ViewModel);
                }

                using (var tc = new TransactionScope())
                {
                    Perfil ObjPerfil = null;

                    if (ViewModel.PerfilId.HasValue)
                        ObjPerfil = Context.Perfil.FirstOrDefault(X => X.PerfilId == ViewModel.PerfilId);
                    else
                    {
                        ObjPerfil = new Perfil();
                        ObjPerfil.UsuarioId = Session.GetUsuarioId();
                        Context.Perfil.Add(ObjPerfil);
                    }

                    ObjPerfil.Nombre = ViewModel.Nombre.ToUpper();
                    ObjPerfil.Apellido = ViewModel.Apellido.ToUpper();
                    ObjPerfil.Dni = ViewModel.Dni;
                    ObjPerfil.Email = ViewModel.Email;

                    Context.SaveChanges();
                    TempData["Mensaje"] = "El Perfil fue procesado exitosamente";
                    tc.Complete();
                }
            }
            catch (Exception ex)
            {
                ViewModel.CargarDatos(ViewModel.PerfilId);
                TryUpdateModel(ViewModel);

                TempData["Mensaje"] = "Por favor, complete los campos requeridos";
                return View(ViewModel);
            }
            return RedirectToAction("ListarPerfiles");
        }
    }
}

PROYECTO-FINANZAS/PROYECTO-FINANZAS.Web/Views/Shared/_Layout.cshtml
@using PROYECTO_FINANZAS.Web.Helpers

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/bundles/css")
</head>
<body>
    <div id="wrapper">
        <nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index", "Dashboard")">Proyecto Finanzas</a>
            </div>
            <div style="color: white; padding: 10px 50px 5px 50px; float: right; font-size: 16px;">
                <a href="@Url.Action("Logout", "Home")" class="btn btn-danger btn-lg square-btn-adjust"><i class="fa fa-eraser"></i> Cerrar Sesión</a>
            </div>
        </nav>
        <!-- /. NAV TOP  -->
        <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
                    <li class="text-center">
                        <img src="@Url.Content("~/Content/img/ImagenAdmin.png")" class="user-image img-responsive" />
                        <h3 style="color:white;">@Session.GetNombrePerfil()</h3>
                    </li>
                    <li>
                        <a class="active-menu" href="@Url.Action("Index", "Dashboard")"><i class="fa fa-dashboard fa-3x"></i> Dashboard</a>
                    </li>
                    <li>
                        <a class="active-menu" href="@Url.Action("ListarPerfiles", "Perfil")"><i class="fa fa-user fa-3x"></i> Perfiles</a>
                    </li>
                    <li>
                        <a class="active-menu" href="@Url.Action("Index", "Dashboard")"><i class="fa fa-money fa-3x"></i> Cuentas Corrientes</a>
                    </li>
                    <li>
                        <a class="active-menu" href="@Url.Action("Index", "Dashboard")"><i class="fa fa-calculator fa-3x"></i>Calculos a Plazo Fijo</a>
                    </li>
                </ul>
            </div>

        </nav>
        <!-- /. NAV SIDE  -->
        <div id="page-wrapper">
            <div id="page-inner">
                @RenderBody()
            </div>
            <!-- /. PAGE INNER  -->
        </div>
        <!-- /. PAGE WRAPPER  -->
    </div>     
    @Scripts.Render("~/bundles/scripts")
</body>
</html>